name: PHP Tests
on: [push]
jobs:
  php:
    name: (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.2', '8.3', '8.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
          tools: cs2pr

      - name: Install Composer dependencies
        run: composer install --no-interaction --classmap-authoritative --no-progress

      - name: Run PHP Code Sniffer and PHP CS Fixer (dry run)
        run: PHP_CS_FIXER_IGNORE_ENV=1 composer run-script phpcs:ci

      - name: Run unit tests
        run: composer run-script phpunit:ci
